### ISSUE TITLE
Different firmware required for motherboard with microphone

### ISSUE THREAD

**Issue by qulet** [Sliicy/8x8x8-LED#4]
![error](https://github.com/Sliicy/8x8x8-LED/assets/30979927/e8103f51-a263-4b6d-8148-6da0c7988698)

> Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again...

Com port selected correctly, switches Boot 1 - 0, Boot2 - 0 Pressing reset at the time of upload does not trigger the upload process?
  Please help
Regards

**Comment by Sliicy** [comment]
Hi @qulet, I found a video explaining some reasons why this may happen:
https://www.youtube.com/watch?v=Rr0tNVy2geg

And someone with a similar issue:
https://community.st.com/t5/stm32cubeprogrammer-mcus/cubeprogrammer-connect-to-uart-interface/td-p/290057

I will admit when I first tried doing this, I had to play around with the 2 boot switches a bit until I got it working. Also, maybe a board might need a lower baud rate to talk properly?

Let me know if these help!

**Comment by qulet** [comment]
Thank you very much for your tips and help.
Now the STM32CubeProgrammer connects to the yellow board. I have uploaded the compiled Bills_iCubeSmart.ino.hex file.
   The 8x8x8 LED.exe program connects to COM4 but the LEDs do not light up.
I tried to re-upload the "icubesmart" Update.hex file, but it also stopped working with the motherboard. Currently, after these attempts, I am in despair because the 8x8x8 RGB cube does not light up.
I am sending the programming log. What am I doing wrong  ?

p.s I couldn't program the yellow board using the Arduino IDE, so I found a compiled .hex file and uploaded it to STM32CubeProgrammer.



[Log.zip](https://github.com/Sliicy/8x8x8-LED/files/12576183/Log.zip)

![Hex](https://github.com/Sliicy/8x8x8-LED/assets/30979927/330a6b0a-d9a7-45b0-9558-9e6fdcfb0d3a)

![led8x8x8RGB](https://github.com/Sliicy/8x8x8-LED/assets/30979927/aae6c69d-3bfe-49f9-b2c7-7daf9102c8a5)


When uploading a hex file BOOT0=1 BOOT1=0 it worked.
After uploading the hex file BOOT0=1 BOOT1=1

Attempting to upload the Release/// Original Firmware 8x8x8 RGB Cube.hex file causes an error:
![error parsing](https://github.com/Sliicy/8x8x8-LED/assets/30979927/5a62b57b-bf42-4351-9e7f-25a5a0f7edaf)
Regards

**Comment by qulet** [comment]
breaking news!
Successfully uploaded the program from the Arduino IDE. BOOT0=1; BOOT1=0

![Arduino_IDE](https://github.com/Sliicy/8x8x8-LED/assets/30979927/2b74484f-7bf4-4db8-a5bc-c8c5d5c7f73b)


After uploading, I set the switch BOOT0=0 BOOT1=1. Three diodes green, red and blue lit up on the yellow board. Serial port conect - Send TestPacket does not work. The diodes do not light up. When I disconnect USB-TTL from the computer, the LEDs RGB light up for a moment.
Changing BOOT1=0 and reconnecting the USB-TTL to the computer port also does not cause the LED to light up after pressing the Send TestPacket button. Baud Rate = 2000000, 38400 all
With USB-TTL plugged in, removing the cube power cable causes the LED RGB to light up momentarily.

After pressing the send button, the LEDs on the USB-TTL interface start pulsating but the RGB LEDs do not light up

**Comment by qulet** [comment]
![kostka](https://github.com/Sliicy/8x8x8-LED/assets/30979927/bf0cb068-d829-4436-8639-563135b4f39d)
My motherboard is a new version, maybe this is the cause of the problems?
![PCB](https://github.com/Sliicy/8x8x8-LED/assets/30979927/7ffb49fa-acad-4f44-ad06-4b671d152e46)
![PCB_1](https://github.com/Sliicy/8x8x8-LED/assets/30979927/b8cbdf7a-f270-4d1e-a827-5f319aec6bc1)
After assembly, the cube worked on the loaded Icubesmart firmware. An attempt to restore the firmware with their software was unsuccessful. I did it with STM32CubeProgramer with the Update.hex file but the cube stopped working, I don't know what to do next?
Arduino seriall monitor : https://drive.google.com/file/d/1l4cyTm7Wo6lb-c71RMsEnZWXc0vSpGwY/view?usp=sharing

**Comment by Sliicy** [comment]
@qulet I think the problem you're facing is that your cube is not getting enough voltage. In my case, I had to make a custom wire to provide enough voltage (5 volts, 2 amps) to the board. In the below photo, the circled blue is the voltage for the LEDs, and the circled green is the USB data +/- connectors. You could just use a separate power source for the LEDs, but I liked having 2 in 1 so I only have to deal with 1 cord:
![signal-2023-09-27-001102](https://github.com/Sliicy/8x8x8-LED/assets/23116873/c2d553bd-260e-4869-873e-4c47867bec33)

**Comment by qulet** [comment]
Thank you for your answer !
My cube is powered by a 5V-2A phone charger and the icubesmart software works well. I managed to upload the botloader (I got the file from the icube smart service), which I deleted while trying to use your software. The cube currently runs on the original firmware.
![IMG20230927201738](https://github.com/Sliicy/8x8x8-LED/assets/30979927/66de8d5f-d786-4ea2-8e9f-d7c94b568031)

**Comment by Sliicy** [comment]
@qulet can you share the bootloader file so I can add it in case anyone else gets stuck and needs it?

**Comment by qulet** [comment]
Icubesmart firmware upload STM32CubeProgrammer.
After uploading the bootloader, you need to upload update.hex with a dedicated software

[BootLoader.zip](https://github.com/Sliicy/8x8x8-LED/files/12754087/BootLoader.zip)

[3D Software and Download Software.zip](https://github.com/Sliicy/8x8x8-LED/files/12754090/3D.Software.and.Download.Software.zip)

**Comment by Sliicy** [comment]
https://github.com/Sliicy/8x8x8-LED/blob/master/Firmware/RGB/Original%20Firmware%208x8x8%20RGB%20Cube.hex
It isn't the same as the one I have in my repo but thank you.

**Comment by qulet** [comment]
You have a different motherboard, mine has a built-in microphone, I think this is the reason for the difference in the bootloader code. Generally, this is probably why your "Bills_iCubeSmart.ino" code doesn't work. The 8x8x8 LED.exe program seems to be OK, because the transmission diode on the USB-TTL interface blinks at a speed proportional to the "speed" slider settings
Regards!
